import type { ManagedCompany } from '@/domain/entities'
import { CompanyAccountStatus } from '@/domain/enums'

export const companiesDummyData: ManagedCompany[] = [
  {
    id: 'co-1',
    name: 'Gulf Hospitality Group',
    type: 'Hotel',
    email: 'ops@gulfhospitality.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-1',
      fullName: 'Fatima Al-Qassim',
      email: 'fatima@gulfhospitality.bh',
      phone: '+973 3344 1100',
    },
    phone: '+973 1722 4400',
    branchesCount: 6,
    activeOrders: 24,
    completedOrders: 412,
    pendingInvoices: 2,
    outstandingBalance: 1840.5,
    status: CompanyAccountStatus.Approved,
    isActive: true,
    createdAt: '2024-03-12T08:00:00.000Z',
  },
  {
    id: 'co-2',
    name: 'Manama Corporate Suites',
    type: 'Corporate',
    email: 'facilities@manamacorporate.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-2',
      fullName: 'Ahmed Al-Mutawa',
      email: 'ahmed@manamacorporate.bh',
      phone: '+973 3355 2201',
    },
    phone: '+973 1788 9900',
    branchesCount: 3,
    activeOrders: 11,
    completedOrders: 198,
    pendingInvoices: 0,
    outstandingBalance: 0,
    status: CompanyAccountStatus.PendingAdminApproval,
    isActive: true,
    createdAt: '2024-05-20T10:30:00.000Z',
  },
  {
    id: 'co-3',
    name: 'Royal Care Medical Center',
    type: 'Healthcare',
    email: 'admin@royalcare.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-3',
      fullName: 'Dr. Laila Hassan',
      email: 'laila@royalcare.bh',
      phone: '+973 3366 3302',
    },
    phone: '+973 1733 5500',
    branchesCount: 2,
    activeOrders: 8,
    completedOrders: 156,
    pendingInvoices: 1,
    outstandingBalance: 620.75,
    status: CompanyAccountStatus.Approved,
    isActive: true,
    createdAt: '2024-06-02T09:15:00.000Z',
  },
  {
    id: 'co-4',
    name: 'Seef Retail Collective',
    type: 'Retail',
    email: 'partners@seefretail.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-4',
      fullName: 'Youssef Nabil',
      email: 'youssef@seefretail.bh',
      phone: '+973 3377 4403',
    },
    phone: '+973 1744 6600',
    branchesCount: 4,
    activeOrders: 15,
    completedOrders: 287,
    pendingInvoices: 3,
    outstandingBalance: 945.2,
    status: CompanyAccountStatus.PendingEmailVerification,
    isActive: true,
    createdAt: '2024-07-18T11:00:00.000Z',
  },
  {
    id: 'co-5',
    name: 'Pearl Tower Residences',
    type: 'Hotel',
    email: 'housekeeping@pearltower.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-5',
      fullName: 'Sara Al-Harbi',
      email: 'sara@pearltower.bh',
      phone: '+973 3388 5504',
    },
    phone: '+973 1755 7700',
    branchesCount: 1,
    activeOrders: 6,
    completedOrders: 94,
    pendingInvoices: 0,
    outstandingBalance: 0,
    status: CompanyAccountStatus.Suspended,
    isActive: false,
    createdAt: '2024-08-05T14:20:00.000Z',
  },
  {
    id: 'co-6',
    name: 'Bahrain Finance Park',
    type: 'Corporate',
    email: 'services@bahrainfinance.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-6',
      fullName: 'Omar Khalid',
      email: 'omar@bahrainfinance.bh',
      phone: '+973 3399 6605',
    },
    phone: '+973 1766 8800',
    branchesCount: 5,
    activeOrders: 19,
    completedOrders: 331,
    pendingInvoices: 1,
    outstandingBalance: 410,
    status: CompanyAccountStatus.Approved,
    isActive: true,
    createdAt: '2024-09-10T08:45:00.000Z',
  },
  {
    id: 'co-7',
    name: 'Al Hidd Wellness Clinic',
    type: 'Healthcare',
    email: 'contact@alhiddwellness.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-7',
      fullName: 'Nour El-Din',
      email: 'nour@alhiddwellness.bh',
      phone: '+973 3310 7706',
    },
    phone: '+973 1777 9900',
    branchesCount: 1,
    activeOrders: 3,
    completedOrders: 67,
    pendingInvoices: 2,
    outstandingBalance: 1280,
    status: CompanyAccountStatus.Approved,
    isActive: true,
    createdAt: '2024-10-01T12:00:00.000Z',
  },
  {
    id: 'co-8',
    name: 'City Center Stores',
    type: 'Retail',
    email: 'ops@citycenterstores.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-8',
      fullName: 'Maya Hassan',
      email: 'maya@citycenterstores.bh',
      phone: '+973 3320 8807',
    },
    phone: '+973 1788 1100',
    branchesCount: 7,
    activeOrders: 31,
    completedOrders: 502,
    pendingInvoices: 4,
    outstandingBalance: 2150.3,
    status: CompanyAccountStatus.Approved,
    isActive: true,
    createdAt: '2024-11-14T16:30:00.000Z',
  },
  {
    id: 'co-9',
    name: 'Legacy Textile Works',
    type: 'Other',
    email: 'info@legacytextile.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-9',
      fullName: 'Karim Farouk',
      email: 'karim@legacytextile.bh',
      phone: '+973 3330 9908',
    },
    phone: '+973 1799 2200',
    branchesCount: 2,
    activeOrders: 0,
    completedOrders: 45,
    pendingInvoices: 0,
    outstandingBalance: 0,
    status: CompanyAccountStatus.Rejected,
    isActive: false,
    createdAt: '2024-12-02T09:00:00.000Z',
  },
  {
    id: 'co-10',
    name: 'Diplomat Hotel & Spa',
    type: 'Hotel',
    email: 'laundry@diplomathotel.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-10',
      fullName: 'Hana Saleh',
      email: 'hana@diplomathotel.bh',
      phone: '+973 3340 1019',
    },
    phone: '+973 1711 3300',
    branchesCount: 2,
    activeOrders: 17,
    completedOrders: 276,
    pendingInvoices: 1,
    outstandingBalance: 355.5,
    status: CompanyAccountStatus.Approved,
    isActive: true,
    createdAt: '2025-01-08T10:10:00.000Z',
  },
  {
    id: 'co-11',
    name: 'Northern Logistics Hub',
    type: 'Corporate',
    email: 'admin@northernlogistics.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-11',
      fullName: 'Layla Mansour',
      email: 'layla@northernlogistics.bh',
      phone: '+973 3350 1120',
    },
    phone: '+973 1722 5500',
    branchesCount: 3,
    activeOrders: 9,
    completedOrders: 143,
    pendingInvoices: 0,
    outstandingBalance: 0,
    status: CompanyAccountStatus.Approved,
    isActive: true,
    createdAt: '2025-02-19T13:25:00.000Z',
  },
  {
    id: 'co-12',
    name: 'Sunrise Boutique Chain',
    type: 'Retail',
    email: 'support@sunriseboutique.bh',
    logoUrl: null,
    responsible: {
      id: 'cr-12',
      fullName: 'Rami Al-Sayed',
      email: 'rami@sunriseboutique.bh',
      phone: '+973 3360 2231',
    },
    phone: '+973 1733 7700',
    branchesCount: 5,
    activeOrders: 12,
    completedOrders: 219,
    pendingInvoices: 2,
    outstandingBalance: 780,
    status: CompanyAccountStatus.Approved,
    isActive: false,
    createdAt: '2025-03-04T15:40:00.000Z',
  },
]
