import type { CompanyDetailsData } from '@/domain/entities/company-details.entity'
import { CompanyAccountStatus, OrderStatus } from '@/domain/enums'

const daysAgo = (days: number) => {
  const d = new Date()
  d.setDate(d.getDate() - days)
  return d.toISOString()
}

const hoursAgo = (hours: number) => {
  const d = new Date()
  d.setHours(d.getHours() - hours)
  return d.toISOString()
}

export const companyDetailsData: CompanyDetailsData = {
  id: 'co-1',
  slug: 'gulf-hospitality-group',
  name: 'Gulf Hospitality Group',
  type: 'Hotel',
  email: 'ops@gulfhospitality.bh',
  phone: '+973 1722 4400',
  logoUrl: null,
  commercialRegistration: 'CR-2024-88421',
  address: 'Building 1240, Road 4025, Block 340, Manama, Bahrain',
  googleMapsLink: 'https://maps.google.com/?q=26.2235,50.5876',
  status: CompanyAccountStatus.Approved,
  isActive: true,
  createdAt: '2024-03-12T08:00:00.000Z',
  responsible: {
    id: 'cr-1',
    fullName: 'Fatima Al-Qassim',
    email: 'fatima@gulfhospitality.bh',
    phone: '+973 3344 1100',
  },

  stats: {
    branches: 6,
    activeOrders: 24,
    completedOrders: 412,
    ordersThisMonth: 47,
    outstandingBalance: 2080,
    totalRevenue: 84_250,
    pendingInvoices: 4,
    overdueInvoices: 2,
  },

  financials: {
    totalInvoices: 48,
    paidInvoices: 42,
    pendingInvoices: 4,
    overdueInvoices: 2,
    totalBilledAmount: 86_330,
    totalPaidAmount: 84_250,
    outstandingBalance: 2_080,
    collectionRate: 97.6,
  },

  alerts: [
    {
      id: 'alert-1',
      type: 'overdue_invoices',
      title: '2 overdue invoices',
      description: 'Total $2,080 — oldest due 14 days ago',
      count: 2,
      severity: 'warning',
    },
    {
      id: 'alert-2',
      type: 'dispatch_ready',
      title: '2 orders ready for dispatch',
      description: 'Awaiting driver assignment',
      count: 2,
      severity: 'info',
    },
  ],

  branches: [
    {
      id: 'br-1',
      name: 'Seef District Branch',
      slug: 'seef-district',
      managerName: 'Ahmed Al-Khalifa',
      phone: '+973 3355 1001',
      email: 'seef@gulfhospitality.bh',
      address: 'Seef Mall, Block 428, Manama',
      googleMapsLink: 'https://maps.google.com/?q=26.2361,50.5314',
      status: 'active',
      activeOrders: 8,
      completedOrders: 124,
      ordersThisMonth: 16,
      outstandingBalance: 640,
      overdueOrders: 1,
      pendingInvoices: 2,
    },
    {
      id: 'br-2',
      name: 'Juffair Tower Branch',
      slug: 'juffair-tower',
      managerName: 'Sara Al-Doseri',
      phone: '+973 3355 1002',
      email: 'juffair@gulfhospitality.bh',
      address: 'Juffair Avenue, Block 332, Juffair',
      googleMapsLink: 'https://maps.google.com/?q=26.2048,50.6076',
      status: 'active',
      activeOrders: 6,
      completedOrders: 98,
      ordersThisMonth: 12,
      outstandingBalance: 420,
      overdueOrders: 0,
      pendingInvoices: 1,
    },
    {
      id: 'br-3',
      name: 'Adliya Boutique Hotel',
      slug: 'adliya-boutique',
      managerName: 'Khalid Mansour',
      phone: '+973 3355 1003',
      email: 'adliya@gulfhospitality.bh',
      address: 'Exhibition Road, Block 338, Adliya',
      googleMapsLink: 'https://maps.google.com/?q=26.2153,50.5832',
      status: 'active',
      activeOrders: 5,
      completedOrders: 87,
      ordersThisMonth: 9,
      outstandingBalance: 520,
      overdueOrders: 1,
      pendingInvoices: 1,
    },
    {
      id: 'br-4',
      name: 'Amwaj Resort',
      slug: 'amwaj-resort',
      managerName: 'Layla Ibrahim',
      phone: '+973 3355 1004',
      email: 'amwaj@gulfhospitality.bh',
      address: 'Amwaj Islands, Block 247, Muharraq',
      googleMapsLink: 'https://maps.google.com/?q=26.2831,50.6524',
      status: 'active',
      activeOrders: 3,
      completedOrders: 56,
      ordersThisMonth: 6,
      outstandingBalance: 300,
      overdueOrders: 0,
      pendingInvoices: 0,
    },
    {
      id: 'br-5',
      name: 'Diplomatic Quarter',
      slug: 'diplomatic-quarter',
      managerName: 'Noor Al-Faisal',
      phone: '+973 3355 1005',
      email: 'diplo@gulfhospitality.bh',
      address: 'Diplomatic Area, Block 317, Manama',
      googleMapsLink: 'https://maps.google.com/?q=26.2285,50.5860',
      status: 'active',
      activeOrders: 2,
      completedOrders: 32,
      ordersThisMonth: 4,
      outstandingBalance: 200,
      overdueOrders: 0,
      pendingInvoices: 0,
    },
    {
      id: 'br-6',
      name: 'Riffa Heritage Inn',
      slug: 'riffa-heritage',
      managerName: 'Mohammed Youssef',
      phone: '+973 3355 1006',
      email: 'riffa@gulfhospitality.bh',
      address: 'Riffa Main Street, Block 901, Riffa',
      googleMapsLink: 'https://maps.google.com/?q=26.1304,50.5550',
      status: 'inactive',
      activeOrders: 0,
      completedOrders: 15,
      ordersThisMonth: 0,
      outstandingBalance: 0,
      overdueOrders: 0,
      pendingInvoices: 0,
    },
  ],

  invoices: [
    { id: 'inv-1', invoiceNumber: 'INV-2025-0048', branchId: 'br-1', branchSlug: 'seef-district', branchName: 'Seef District Branch', invoiceDate: daysAgo(3), dueDate: daysAgo(-7), amount: 1_420, paidAmount: 0, status: 'pending' },
    { id: 'inv-2', invoiceNumber: 'INV-2025-0047', branchId: 'br-2', branchSlug: 'juffair-tower', branchName: 'Juffair Tower Branch', invoiceDate: daysAgo(10), dueDate: daysAgo(-3), amount: 890, paidAmount: 0, status: 'pending' },
    { id: 'inv-3', invoiceNumber: 'INV-2025-0046', branchId: 'br-1', branchSlug: 'seef-district', branchName: 'Seef District Branch', invoiceDate: daysAgo(18), dueDate: daysAgo(4), amount: 1_240, paidAmount: 0, status: 'overdue' },
    { id: 'inv-4', invoiceNumber: 'INV-2025-0045', branchId: 'br-3', branchSlug: 'adliya-boutique', branchName: 'Adliya Boutique Hotel', invoiceDate: daysAgo(25), dueDate: daysAgo(11), amount: 840, paidAmount: 0, status: 'overdue' },
    { id: 'inv-5', invoiceNumber: 'INV-2025-0044', branchId: 'br-1', branchSlug: 'seef-district', branchName: 'Seef District Branch', invoiceDate: daysAgo(32), dueDate: daysAgo(18), amount: 1_560, paidAmount: 1_560, status: 'paid' },
    { id: 'inv-6', invoiceNumber: 'INV-2025-0043', branchId: 'br-2', branchSlug: 'juffair-tower', branchName: 'Juffair Tower Branch', invoiceDate: daysAgo(40), dueDate: daysAgo(26), amount: 2_100, paidAmount: 2_100, status: 'paid' },
    { id: 'inv-7', invoiceNumber: 'INV-2025-0042', branchId: 'br-4', branchSlug: 'amwaj-resort', branchName: 'Amwaj Resort', invoiceDate: daysAgo(48), dueDate: daysAgo(34), amount: 980, paidAmount: 980, status: 'paid' },
    { id: 'inv-8', invoiceNumber: 'INV-2025-0041', branchId: 'br-5', branchSlug: 'diplomatic-quarter', branchName: 'Diplomatic Quarter', invoiceDate: daysAgo(55), dueDate: daysAgo(41), amount: 1_750, paidAmount: 1_750, status: 'paid' },
    { id: 'inv-9', invoiceNumber: 'INV-2025-0040', branchId: 'br-3', branchSlug: 'adliya-boutique', branchName: 'Adliya Boutique Hotel', invoiceDate: daysAgo(60), dueDate: daysAgo(46), amount: 1_120, paidAmount: 1_120, status: 'paid' },
    { id: 'inv-10', invoiceNumber: 'INV-2025-0039', branchId: 'br-1', branchSlug: 'seef-district', branchName: 'Seef District Branch', invoiceDate: daysAgo(65), dueDate: daysAgo(51), amount: 760, paidAmount: 760, status: 'paid' },
    { id: 'inv-11', invoiceNumber: 'INV-2025-0038', branchId: 'br-2', branchSlug: 'juffair-tower', branchName: 'Juffair Tower Branch', invoiceDate: daysAgo(70), dueDate: daysAgo(56), amount: 1_340, paidAmount: 1_340, status: 'paid' },
    { id: 'inv-12', invoiceNumber: 'INV-2025-0037', branchId: 'br-4', branchSlug: 'amwaj-resort', branchName: 'Amwaj Resort', invoiceDate: daysAgo(75), dueDate: daysAgo(61), amount: 920, paidAmount: 920, status: 'paid' },
  ],

  recentOrders: [
    { id: 'ord-1', orderNumber: 'ORD-2025-0412', branchId: 'br-1', branchSlug: 'seef-district', branchName: 'Seef District Branch', status: OrderStatus.ReadyForDelivery, itemsCount: 34, bagsCount: 4, pickupDate: hoursAgo(8), deliveryDate: hoursAgo(-4) },
    { id: 'ord-2', orderNumber: 'ORD-2025-0411', branchId: 'br-2', branchSlug: 'juffair-tower', branchName: 'Juffair Tower Branch', status: OrderStatus.InLaundry, itemsCount: 22, bagsCount: 3, pickupDate: hoursAgo(6), deliveryDate: hoursAgo(-8) },
    { id: 'ord-3', orderNumber: 'ORD-2025-0410', branchId: 'br-1', branchSlug: 'seef-district', branchName: 'Seef District Branch', status: OrderStatus.ReadyForDelivery, itemsCount: 18, bagsCount: 2, pickupDate: hoursAgo(12), deliveryDate: hoursAgo(-2) },
    { id: 'ord-4', orderNumber: 'ORD-2025-0409', branchId: 'br-3', branchSlug: 'adliya-boutique', branchName: 'Adliya Boutique Hotel', status: OrderStatus.PickedUp, itemsCount: 45, bagsCount: 5, pickupDate: hoursAgo(2), deliveryDate: hoursAgo(-14) },
    { id: 'ord-5', orderNumber: 'ORD-2025-0408', branchId: 'br-4', branchSlug: 'amwaj-resort', branchName: 'Amwaj Resort', status: OrderStatus.Delivered, itemsCount: 28, bagsCount: 3, pickupDate: daysAgo(2), deliveryDate: daysAgo(1) },
    { id: 'ord-6', orderNumber: 'ORD-2025-0407', branchId: 'br-5', branchSlug: 'diplomatic-quarter', branchName: 'Diplomatic Quarter', status: OrderStatus.Delivered, itemsCount: 15, bagsCount: 2, pickupDate: daysAgo(3), deliveryDate: daysAgo(2) },
    { id: 'ord-7', orderNumber: 'ORD-2025-0406', branchId: 'br-1', branchSlug: 'seef-district', branchName: 'Seef District Branch', status: OrderStatus.Delivered, itemsCount: 52, bagsCount: 6, pickupDate: daysAgo(4), deliveryDate: daysAgo(3) },
    { id: 'ord-8', orderNumber: 'ORD-2025-0405', branchId: 'br-2', branchSlug: 'juffair-tower', branchName: 'Juffair Tower Branch', status: OrderStatus.Delivered, itemsCount: 19, bagsCount: 2, pickupDate: daysAgo(5), deliveryDate: daysAgo(4) },
    { id: 'ord-9', orderNumber: 'ORD-2025-0404', branchId: 'br-3', branchSlug: 'adliya-boutique', branchName: 'Adliya Boutique Hotel', status: OrderStatus.OrderCreated, itemsCount: 12, bagsCount: 1, pickupDate: daysAgo(1), deliveryDate: daysAgo(-2) },
    { id: 'ord-10', orderNumber: 'ORD-2025-0403', branchId: 'br-4', branchSlug: 'amwaj-resort', branchName: 'Amwaj Resort', status: OrderStatus.InLaundry, itemsCount: 31, bagsCount: 4, pickupDate: daysAgo(2), deliveryDate: daysAgo(0) },
    { id: 'ord-11', orderNumber: 'ORD-2025-0402', branchId: 'br-1', branchSlug: 'seef-district', branchName: 'Seef District Branch', status: OrderStatus.Delivered, itemsCount: 24, bagsCount: 3, pickupDate: daysAgo(6), deliveryDate: daysAgo(5) },
    { id: 'ord-12', orderNumber: 'ORD-2025-0401', branchId: 'br-2', branchSlug: 'juffair-tower', branchName: 'Juffair Tower Branch', status: OrderStatus.PickedUp, itemsCount: 16, bagsCount: 2, pickupDate: daysAgo(1), deliveryDate: daysAgo(-1) },
  ],

  activities: [
    { id: 'act-1', type: 'order_created', description: 'New order ORD-2025-0412 created', user: 'Fatima Al-Qassim', timestamp: hoursAgo(8) },
    { id: 'act-2', type: 'driver_assigned', description: 'Driver assigned to ORD-2025-0411', user: 'System', timestamp: hoursAgo(7) },
    { id: 'act-3', type: 'order_picked_up', description: 'Order ORD-2025-0411 picked up from Juffair Tower', user: 'Ahmed Hassan', timestamp: hoursAgo(6) },
    { id: 'act-4', type: 'invoice_generated', description: 'Invoice INV-2025-0048 generated — $1,420', user: 'System', timestamp: hoursAgo(5) },
    { id: 'act-5', type: 'payment_received', description: 'Payment $1,560 received for INV-2025-0044', user: 'Fatima Al-Qassim', timestamp: daysAgo(1) },
    { id: 'act-6', type: 'order_delivered', description: 'Order ORD-2025-0408 delivered to Amwaj Resort', user: 'Omar Khalid', timestamp: daysAgo(1) },
    { id: 'act-7', type: 'order_created', description: 'New order ORD-2025-0409 created', user: 'Khalid Mansour', timestamp: hoursAgo(2) },
    { id: 'act-8', type: 'status_changed', description: 'Order ORD-2025-0410 marked as Ready for Delivery', user: 'System', timestamp: hoursAgo(3) },
    { id: 'act-9', type: 'branch_added', description: 'Riffa Heritage Inn branch added', user: 'Admin', timestamp: daysAgo(5) },
    { id: 'act-10', type: 'payment_received', description: 'Payment $2,100 received for INV-2025-0043', user: 'Fatima Al-Qassim', timestamp: daysAgo(8) },
    { id: 'act-11', type: 'order_delivered', description: 'Order ORD-2025-0407 delivered to Diplomatic Quarter', user: 'Youssef Ali', timestamp: daysAgo(2) },
    { id: 'act-12', type: 'invoice_generated', description: 'Invoice INV-2025-0047 generated — $890', user: 'System', timestamp: daysAgo(10) },
  ],
}
