import { OrderStatus } from '@/domain/enums'
import type { RecentOrder } from '@/domain/entities'

export const recentOrdersDummyData: RecentOrder[] = [
  {
    id: 'ord-1',
    orderNumber: 'ORD-2841',
    customerId: 'cust-12',
    customerName: 'Ahmed Al-Rashid',
    branchId: 'br-1',
    branchName: 'Downtown Branch',
    pickupAt: '2026-06-09T08:30:00.000Z',
    expectedDeliveryAt: '2026-06-10T14:00:00.000Z',
    bags: ['B-014', 'B-015', 'B-016'],
    driver: {
      id: 'drv-3',
      fullName: 'Khalid Hassan',
      email: 'khalid.hassan@cleno.bh',
      avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Khalid',
    },
    status: OrderStatus.OnTheWayToLaundry,
  },
  {
    id: 'ord-2',
    orderNumber: 'ORD-2839',
    customerId: 'cust-8',
    customerName: 'Sara Mohammed',
    branchId: 'br-2',
    branchName: 'Marina Branch',
    pickupAt: '2026-06-09T07:15:00.000Z',
    expectedDeliveryAt: '2026-06-10T11:30:00.000Z',
    bags: ['B-021', 'B-022'],
    driver: null,
    status: OrderStatus.OrderCreated,
  },
  {
    id: 'ord-3',
    orderNumber: 'ORD-2835',
    customerId: 'cust-21',
    customerName: 'Omar Farouk',
    branchId: 'br-1',
    branchName: 'Downtown Branch',
    pickupAt: '2026-06-08T16:45:00.000Z',
    expectedDeliveryAt: '2026-06-09T18:00:00.000Z',
    bags: ['B-008'],
    driver: {
      id: 'drv-1',
      fullName: 'Youssef Ali',
      email: 'youssef.ali@cleno.bh',
      avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Youssef',
    },
    status: OrderStatus.InLaundry,
  },
  {
    id: 'ord-4',
    orderNumber: 'ORD-2830',
    customerId: 'cust-5',
    customerName: 'Layla Ibrahim',
    branchId: 'br-3',
    branchName: 'North District',
    pickupAt: '2026-06-08T10:00:00.000Z',
    expectedDeliveryAt: '2026-06-09T12:00:00.000Z',
    bags: ['B-031', 'B-032', 'B-033', 'B-034'],
    driver: {
      id: 'drv-2',
      fullName: 'Faisal Nasser',
      email: 'faisal.nasser@cleno.bh',
      avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Faisal',
    },
    status: OrderStatus.ReadyForDelivery,
  },
  {
    id: 'ord-5',
    orderNumber: 'ORD-2824',
    customerId: 'cust-17',
    customerName: 'Nour El-Din',
    branchId: 'br-2',
    branchName: 'Marina Branch',
    pickupAt: '2026-06-07T09:20:00.000Z',
    expectedDeliveryAt: '2026-06-08T15:00:00.000Z',
    bags: ['B-005', 'B-006'],
    driver: {
      id: 'drv-4',
      fullName: 'Hassan Kareem',
      email: 'hassan.kareem@cleno.bh',
      avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Hassan',
    },
    status: OrderStatus.Delivered,
  },
  {
    id: 'ord-6',
    orderNumber: 'ORD-2820',
    customerId: 'cust-33',
    customerName: 'Mariam Saleh',
    branchId: 'br-1',
    branchName: 'Downtown Branch',
    pickupAt: '2026-06-07T14:10:00.000Z',
    expectedDeliveryAt: '2026-06-08T20:00:00.000Z',
    bags: ['B-041'],
    driver: null,
    status: OrderStatus.InLaundry,
  },
  {
    id: 'ord-7',
    orderNumber: 'ORD-2815',
    customerId: 'cust-9',
    customerName: 'Tariq Mansour',
    branchId: 'br-3',
    branchName: 'North District',
    pickupAt: '2026-06-06T11:00:00.000Z',
    expectedDeliveryAt: '2026-06-07T16:30:00.000Z',
    bags: ['B-012', 'B-013'],
    driver: {
      id: 'drv-3',
      fullName: 'Khalid Hassan',
      email: 'khalid.hassan@cleno.bh',
      avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Khalid',
    },
    status: OrderStatus.Delivered,
  },
  {
    id: 'ord-8',
    orderNumber: 'ORD-2810',
    customerId: 'cust-44',
    customerName: 'Hana Zaki',
    branchId: 'br-2',
    branchName: 'Marina Branch',
    pickupAt: '2026-06-06T08:45:00.000Z',
    expectedDeliveryAt: '2026-06-07T10:00:00.000Z',
    bags: ['B-027', 'B-028', 'B-029'],
    driver: {
      id: 'drv-1',
      fullName: 'Youssef Ali',
      email: 'youssef.ali@cleno.bh',
      avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Youssef',
    },
    status: OrderStatus.OnTheWayToLaundry,
  },
]
