import type { ManagedOrder, OrderDriver } from '@/domain/entities'
import { OrderStatus } from '@/domain/enums'

export const assignableDriversDummyData: OrderDriver[] = [
  {
    id: 'drv-1',
    fullName: 'Youssef Ali',
    email: 'youssef.ali@cleno.bh',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Youssef',
  },
  {
    id: 'drv-2',
    fullName: 'Faisal Nasser',
    email: 'faisal.nasser@cleno.bh',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Faisal',
  },
  {
    id: 'drv-3',
    fullName: 'Khalid Hassan',
    email: 'khalid.hassan@cleno.bh',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Khalid',
  },
  {
    id: 'drv-4',
    fullName: 'Hassan Kareem',
    email: 'hassan.kareem@cleno.bh',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Hassan',
  },
  {
    id: 'drv-5',
    fullName: 'Mahmoud Saeed',
    email: 'mahmoud.saeed@cleno.bh',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Mahmoud',
  },
  {
    id: 'drv-6',
    fullName: 'Rashid Al-Otaibi',
    email: 'rashid.otaibi@cleno.bh',
    avatarUrl: 'https://api.dicebear.com/9.x/avataaars/svg?seed=Rashid',
  },
]

const drivers = {
  youssef: assignableDriversDummyData[0]!,
  faisal: assignableDriversDummyData[1]!,
  khalid: assignableDriversDummyData[2]!,
  hassan: assignableDriversDummyData[3]!,
  mahmoud: assignableDriversDummyData[4]!,
  rashid: assignableDriversDummyData[5]!,
} as const

export const ordersTableDummyData: ManagedOrder[] = [
  {
    id: 'ord-1',
    orderNumber: 'ORD-2841',
    company: {
      id: 'co-1',
      name: 'Gulf Hospitality Group',
      email: 'ops@gulfhospitality.bh',
      type: 'Hotel',
      logoUrl: null,
    },
    branchId: 'br-1',
    branchName: 'Downtown Branch',
    pickupAt: '2026-06-09T08:30:00.000Z',
    expectedDeliveryAt: '2026-06-10T14:00:00.000Z',
    bags: ['B-014', 'B-015', 'B-016'],
    driver: drivers.khalid,
    status: OrderStatus.OnTheWayToLaundry,
  },
  {
    id: 'ord-2',
    orderNumber: 'ORD-2839',
    company: {
      id: 'co-2',
      name: 'Manama Corporate Suites',
      email: 'facilities@manamacorporate.bh',
      type: 'Corporate',
      logoUrl: null,
    },
    branchId: 'br-2',
    branchName: 'Marina Branch',
    pickupAt: '2026-06-09T07:15:00.000Z',
    expectedDeliveryAt: '2026-06-10T11:30:00.000Z',
    bags: ['B-021', 'B-022'],
    driver: null,
    status: OrderStatus.OrderCreated,
  },
  {
    id: 'ord-3',
    orderNumber: 'ORD-2835',
    company: {
      id: 'co-3',
      name: 'Royal Care Medical Center',
      email: 'admin@royalcare.bh',
      type: 'Healthcare',
      logoUrl: null,
    },
    branchId: 'br-1',
    branchName: 'North Wing',
    pickupAt: '2026-06-08T16:45:00.000Z',
    expectedDeliveryAt: '2026-06-09T18:00:00.000Z',
    bags: ['B-008'],
    driver: drivers.youssef,
    status: OrderStatus.InLaundry,
  },
  {
    id: 'ord-4',
    orderNumber: 'ORD-2830',
    company: {
      id: 'co-4',
      name: 'Seef Retail Collective',
      email: 'partners@seefretail.bh',
      type: 'Retail',
      logoUrl: null,
    },
    branchId: 'br-3',
    branchName: 'North District',
    pickupAt: '2026-06-08T10:00:00.000Z',
    expectedDeliveryAt: '2026-06-09T12:00:00.000Z',
    bags: ['B-031', 'B-032', 'B-033', 'B-034'],
    driver: drivers.faisal,
    status: OrderStatus.ReadyForDelivery,
  },
  {
    id: 'ord-5',
    orderNumber: 'ORD-2824',
    company: {
      id: 'co-2',
      name: 'Manama Corporate Suites',
      email: 'facilities@manamacorporate.bh',
      type: 'Corporate',
      logoUrl: null,
    },
    branchId: 'br-2',
    branchName: 'Marina Branch',
    pickupAt: '2026-06-07T09:20:00.000Z',
    expectedDeliveryAt: '2026-06-08T15:00:00.000Z',
    bags: ['B-005', 'B-006'],
    driver: drivers.hassan,
    status: OrderStatus.Delivered,
  },
  {
    id: 'ord-6',
    orderNumber: 'ORD-2820',
    company: {
      id: 'co-1',
      name: 'Gulf Hospitality Group',
      email: 'ops@gulfhospitality.bh',
      type: 'Hotel',
      logoUrl: null,
    },
    branchId: 'br-1',
    branchName: 'Downtown Branch',
    pickupAt: '2026-06-07T14:10:00.000Z',
    expectedDeliveryAt: '2026-06-08T20:00:00.000Z',
    bags: ['B-041'],
    driver: null,
    status: OrderStatus.InLaundry,
  },
  {
    id: 'ord-7',
    orderNumber: 'ORD-2815',
    company: {
      id: 'co-5',
      name: 'Bahrain Sports Club',
      email: 'admin@bsc.bh',
      type: 'Sports',
      logoUrl: null,
    },
    branchId: 'br-3',
    branchName: 'North District',
    pickupAt: '2026-06-06T11:00:00.000Z',
    expectedDeliveryAt: '2026-06-07T16:30:00.000Z',
    bags: ['B-012', 'B-013'],
    driver: drivers.khalid,
    status: OrderStatus.Delivered,
  },
  {
    id: 'ord-8',
    orderNumber: 'ORD-2810',
    company: {
      id: 'co-4',
      name: 'Seef Retail Collective',
      email: 'partners@seefretail.bh',
      type: 'Retail',
      logoUrl: null,
    },
    branchId: 'br-2',
    branchName: 'Seef Mall',
    pickupAt: '2026-06-06T08:45:00.000Z',
    expectedDeliveryAt: '2026-06-07T10:00:00.000Z',
    bags: ['B-027', 'B-028', 'B-029'],
    driver: drivers.youssef,
    status: OrderStatus.OnTheWayToLaundry,
  },
  {
    id: 'ord-9',
    orderNumber: 'ORD-2805',
    company: {
      id: 'co-3',
      name: 'Royal Care Medical Center',
      email: 'admin@royalcare.bh',
      type: 'Healthcare',
      logoUrl: null,
    },
    branchId: 'br-4',
    branchName: 'Emergency Unit',
    pickupAt: '2026-06-05T13:30:00.000Z',
    expectedDeliveryAt: '2026-06-06T09:00:00.000Z',
    bags: ['B-050', 'B-051'],
    driver: drivers.mahmoud,
    status: OrderStatus.ReadyForDelivery,
  },
  {
    id: 'ord-10',
    orderNumber: 'ORD-2798',
    company: {
      id: 'co-6',
      name: 'Pearl Residences',
      email: 'concierge@pearlres.bh',
      type: 'Residential',
      logoUrl: null,
    },
    branchId: 'br-5',
    branchName: 'Tower A',
    pickupAt: '2026-06-05T07:00:00.000Z',
    expectedDeliveryAt: '2026-06-06T14:00:00.000Z',
    bags: ['B-060'],
    driver: null,
    status: OrderStatus.OrderCreated,
  },
  {
    id: 'ord-11',
    orderNumber: 'ORD-2792',
    company: {
      id: 'co-1',
      name: 'Gulf Hospitality Group',
      email: 'ops@gulfhospitality.bh',
      type: 'Hotel',
      logoUrl: null,
    },
    branchId: 'br-6',
    branchName: 'Airport Hotel',
    pickupAt: '2026-06-04T18:20:00.000Z',
    expectedDeliveryAt: '2026-06-05T22:00:00.000Z',
    bags: ['B-070', 'B-071', 'B-072', 'B-073'],
    driver: drivers.rashid,
    status: OrderStatus.InLaundry,
  },
  {
    id: 'ord-12',
    orderNumber: 'ORD-2786',
    company: {
      id: 'co-2',
      name: 'Manama Corporate Suites',
      email: 'facilities@manamacorporate.bh',
      type: 'Corporate',
      logoUrl: null,
    },
    branchId: 'br-7',
    branchName: 'Business Bay',
    pickupAt: '2026-06-04T10:45:00.000Z',
    expectedDeliveryAt: '2026-06-05T16:00:00.000Z',
    bags: ['B-080', 'B-081'],
    driver: drivers.faisal,
    status: OrderStatus.Delivered,
  },
]
