import type { OperationalBag, OperationalBagStats } from '@/domain/entities'
import { OperationalBagStatus, OperationalBagSystemStatus } from '@/domain/enums'

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString()
const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60 * 1000).toISOString()
const daysAgo = (days: number) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString()

export const operationalBagsDummyData: OperationalBag[] = [
  {
    id: 'bag-1',
    bagId: 'BAG-001',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.Assigned,
    currentOrderId: 'ord-1025',
    currentOrderNumber: 'ORD-1025',
    customerId: 'co-1',
    customerName: 'Gulf Hospitality Group',
    customerSlug: 'gulf-hospitality-group',
    updatedAt: minutesAgo(5),
  },
  {
    id: 'bag-2',
    bagId: 'BAG-002',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.Processing,
    currentOrderId: 'ord-1024',
    currentOrderNumber: 'ORD-1024',
    customerId: 'co-2',
    customerName: 'Riyadh Grand Hotel',
    customerSlug: 'riyadh-grand-hotel',
    updatedAt: minutesAgo(18),
  },
  {
    id: 'bag-3',
    bagId: 'BAG-003',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.Ready,
    currentOrderId: null,
    currentOrderNumber: null,
    customerId: null,
    customerName: null,
    customerSlug: null,
    updatedAt: hoursAgo(2),
  },
  {
    id: 'bag-4',
    bagId: 'BAG-004',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.OnTheWay,
    currentOrderId: 'ord-1022',
    currentOrderNumber: 'ORD-1022',
    customerId: 'co-3',
    customerName: 'Al Faisaliah Suites',
    customerSlug: 'al-faisaliah-suites',
    updatedAt: hoursAgo(1),
  },
  {
    id: 'bag-5',
    bagId: 'BAG-005',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.InTransit,
    currentOrderId: 'ord-1020',
    currentOrderNumber: 'ORD-1020',
    customerId: 'co-4',
    customerName: 'Novotel Business Bay',
    customerSlug: 'novotel-business-bay',
    updatedAt: minutesAgo(42),
  },
  {
    id: 'bag-6',
    bagId: 'BAG-006',
    systemStatus: OperationalBagSystemStatus.Inactive,
    operationalStatus: OperationalBagStatus.Ready,
    currentOrderId: null,
    currentOrderNumber: null,
    customerId: null,
    customerName: null,
    customerSlug: null,
    updatedAt: daysAgo(3),
  },
  {
    id: 'bag-7',
    bagId: 'BAG-007',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.Missing,
    currentOrderId: 'ord-1018',
    currentOrderNumber: 'ORD-1018',
    customerId: 'co-5',
    customerName: 'Hyatt Regency',
    customerSlug: 'hyatt-regency',
    updatedAt: hoursAgo(6),
  },
  {
    id: 'bag-8',
    bagId: 'BAG-008',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.Processing,
    currentOrderId: 'ord-1017',
    currentOrderNumber: 'ORD-1017',
    customerId: 'co-1',
    customerName: 'Gulf Hospitality Group',
    customerSlug: 'gulf-hospitality-group',
    updatedAt: minutesAgo(90),
  },
  {
    id: 'bag-9',
    bagId: 'BAG-009',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.Assigned,
    currentOrderId: 'ord-1015',
    currentOrderNumber: 'ORD-1015',
    customerId: 'co-6',
    customerName: 'Marriott Downtown',
    customerSlug: 'marriott-downtown',
    updatedAt: hoursAgo(4),
  },
  {
    id: 'bag-10',
    bagId: 'BAG-010',
    systemStatus: OperationalBagSystemStatus.Inactive,
    operationalStatus: OperationalBagStatus.Ready,
    currentOrderId: null,
    currentOrderNumber: null,
    customerId: null,
    customerName: null,
    customerSlug: null,
    updatedAt: daysAgo(1),
  },
  {
    id: 'bag-11',
    bagId: 'BAG-011',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.Ready,
    currentOrderId: null,
    currentOrderNumber: null,
    customerId: null,
    customerName: null,
    customerSlug: null,
    updatedAt: hoursAgo(3),
  },
  {
    id: 'bag-12',
    bagId: 'BAG-012',
    systemStatus: OperationalBagSystemStatus.Active,
    operationalStatus: OperationalBagStatus.Missing,
    currentOrderId: 'ord-1012',
    currentOrderNumber: 'ORD-1012',
    customerId: 'co-2',
    customerName: 'Riyadh Grand Hotel',
    customerSlug: 'riyadh-grand-hotel',
    updatedAt: daysAgo(2),
  },
]

export const computeOperationalBagStats = (bags: OperationalBag[]): OperationalBagStats => ({
  totalBags: bags.length,
  activeBags: bags.filter((b) => b.systemStatus === OperationalBagSystemStatus.Active).length,
  inactiveBags: bags.filter((b) => b.systemStatus === OperationalBagSystemStatus.Inactive).length,
  assignedBags: bags.filter((b) => b.operationalStatus === OperationalBagStatus.Assigned).length,
  processingBags: bags.filter((b) => b.operationalStatus === OperationalBagStatus.Processing).length,
  missingBags: bags.filter((b) => b.operationalStatus === OperationalBagStatus.Missing).length,
  readyBags: bags.filter((b) => b.operationalStatus === OperationalBagStatus.Ready).length,
})

export const statSparklineTrends: Record<string, number[]> = {
  totalBags: [18, 20, 19, 22, 21, 23, 24],
  activeBags: [15, 16, 17, 18, 17, 19, 20],
  inactiveBags: [3, 4, 2, 4, 4, 4, 4],
  assignedBags: [4, 5, 6, 5, 7, 6, 5],
  processingBags: [3, 4, 3, 5, 4, 6, 5],
  missingBags: [1, 2, 1, 3, 2, 2, 2],
  readyBags: [5, 6, 7, 6, 8, 7, 8],
}
