export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
  },
  users: {
    me: '/users/me',
    byId: (id: string) => `/users/${id}`,
    adminAll: '/users/admin/all',
    assignableRoles: '/users/assignable-roles',
    create: '/users/create',
    forEdit: (id: string) => `/users/admin/${id}/for-edit`,
    adminById: (id: string) => `/users/admin/${id}`,
    update: (id: string) => `/users/${id}`,
    status: (id: string) => `/users/${id}/status`,
    bulkStatus: '/users/bulk-status',
    bulkDelete: '/users',
  },
  permissions: {
    list: '/Permissions',
  },
  roles: {
    create: '/Roles/create',
    all: '/Roles/all',
    setFeatured: '/Roles/set-featured',
    permissions: (roleSlug: string) => `/Roles/${roleSlug}/permissions`,
    assignUser: '/Roles/assign-user',
    unassignUser: '/Roles/unassign-user',
    users: (roleSlug: string) => `/Roles/${roleSlug}/users`,
    availableUsers: (roleSlug: string) => `/Roles/${roleSlug}/available-users`,
    bySlug: (roleSlug: string) => `/Roles/${roleSlug}`,
  },
  companies: {
    adminAll: '/Companies/admin/all',
    create: '/Companies/create',
    profile: (slug: string) => `/Companies/${slug}`,
    activity: (slug: string) => `/Companies/${slug}/activity`,
    orders: (slug: string) => `/Companies/${slug}/orders`,
    invoices: (slug: string) => `/Companies/${slug}/invoices`,
    branches: (slug: string) => `/Companies/${slug}/branches`,
    forEdit: (slug: string) => `/Companies/${slug}/for-edit`,
    update: (slug: string) => `/Companies/${slug}`,
    toggleActive: '/Companies/toggle-active',
    delete: '/Companies',
    approve: '/Companies/approve',
    reject: '/Companies/reject',
    dropdown: '/companies/dropdown',
  },
  bags: {
    stats: '/Bags/admin/stats',
    adminAll: '/Bags/admin/all',
    dropdown: '/bags/dropdown',
    create: '/Bags/create',
    bySlug: (slug: string) => `/Bags/${slug}`,
  },
  fileUpload: {
    upload: '/FileUpload/upload',
    uploadMultiple: '/FileUpload/upload-multiple',
    download: '/FileUpload/download',
    delete: '/FileUpload/delete',
    deleteFolder: '/FileUpload/delete-folder',
  },
  orders: {
    adminDashboard: '/orders/admin/dashboard',
    adminAll: '/orders/admin/all',
    adminBySlug: (slug: string) => `/orders/admin/${slug}`,
    adminTracking: (slug: string) => `/orders/admin/${slug}/tracking`,
    adminStatus: (slug: string) => `/orders/admin/${slug}/status`,
    adminDriver: (slug: string) => `/orders/admin/${slug}/driver`,
  },
  drivers: {
    adminAll: '/drivers/admin/all',
    adminBySlug: (slug: string) => `/drivers/admin/${slug}`,
    dropdown: '/drivers/dropdown',
    create: '/drivers/create',
    update: (slug: string) => `/drivers/${slug}`,
    toggleStatus: (slug: string) => `/drivers/${slug}/status`,
    delete: (slug: string) => `/drivers/${slug}`,
  },
  laundry: {
    boardStats: '/orders/laundry/board-stats',
    overdueAlert: '/orders/laundry/overdue-alert',
    board: '/orders/laundry',
    bulkStatus: '/orders/laundry/bulk-status',
    notes: (slug: string) => `/orders/${slug}/notes`,
    bags: (slug: string) => `/orders/${slug}/bags`,
    bagById: (slug: string, assignmentId: string) => `/orders/${slug}/bags/${assignmentId}`,
    incidents: (slug: string) => `/orders/${slug}/incidents`,
  },
  incidents: {
    adminAll: '/incidents/admin/all',
    bySlug: (slug: string) => `/incidents/${slug}`,
    update: (slug: string) => `/incidents/${slug}`,
    delete: (slug: string) => `/incidents/${slug}`,
    replies: (slug: string) => `/incidents/${slug}/replies`,
    replyById: (slug: string, replyId: string) => `/incidents/${slug}/replies/${replyId}`,
    orderIncidents: (orderSlug: string) => `/orders/${orderSlug}/incidents`,
  },
  dashboard: {
    kpis: '/dashboard/kpis',
    orderVolume: '/dashboard/order-volume',
    activeDrivers: '/dashboard/active-drivers',
    alerts: '/dashboard/alerts',
    recentOrders: '/dashboard/recent-orders',
    activity: '/dashboard/activity',
  },
  timeSlots: {
    all: '/time-slots/all',
    forEdit: (slug: string) => `/time-slots/${slug}/for-edit`,
    create: '/time-slots/create',
    update: (slug: string) => `/time-slots/${slug}`,
    toggleActive: '/time-slots/toggle-active',
  },
  laundryItems: {
    adminAll: '/laundry-items/admin/all',
    catalog: '/laundry-items/catalog',
    create: '/laundry-items/create',
    update: (slug: string) => `/laundry-items/${slug}`,
    toggleActive: '/laundry-items/toggle-active',
    delete: '/laundry-items',
  },
  profile: {
    me: '/profile/me',
    update: '/profile/me',
    changePassword: '/profile/change-password',
    avatar: '/profile/avatar',
    activity: '/profile/activity',
    sessions: '/profile/sessions',
    sessionById: (id: string) => `/profile/sessions/${id}`,
    sessionsAll: '/profile/sessions/all',
    twoFactor: '/profile/two-factor',
    notifications: '/profile/preferences/notifications',
    appearance: '/profile/preferences/appearance',
    preferences: '/profile/preferences/general',
  },
} as const
